-- AlterEnum (kept in its own migration: new enum values cannot be used in the
-- same transaction that adds them). IF NOT EXISTS makes a manual apply followed
-- by a later `migrate deploy` a harmless no-op.
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'COMMENT_REPLY';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'REPORT_READY';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'LEADER_CHANGED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'MEMBER_REMOVED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'ROLE_SUGGESTION_RECEIVED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'ROLE_SUGGESTION_RESOLVED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'GROUP_CREATED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'DEPARTMENT_CREATED';
ALTER TYPE "AlertType" ADD VALUE IF NOT EXISTS 'USER_REGISTERED';
