import ReactMarkdown from "react-markdown";

interface Props {
  narrative: string;
}

export function Narrative({ narrative }: Props) {
  return (
    <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
      <h2 className="text-sm font-semibold text-slate-700 mb-4">
        <span className="font-mono text-xs text-slate-400 mr-1">Phase 6 ·</span>
        Explainable Fairness Report
      </h2>
      <div className="text-slate-600 text-sm leading-relaxed space-y-3 [&_strong]:font-semibold [&_strong]:text-slate-800 [&_p]:mb-0">
        <ReactMarkdown>{narrative}</ReactMarkdown>
      </div>
      <p className="mt-4 text-xs text-slate-400 italic">
        Generated by Gemini · This narrative is informational only and does not assign grades or replace instructor judgment.
      </p>
    </div>
  );
}
