import { useState } from "react";
import ReactMarkdown from "react-markdown";
import type { NarrativeResponse } from "@shared/types";

interface Props {
  narrative: string | null;
  projectId: number;
}

export function Narrative({ narrative: initialNarrative, projectId }: Props) {
  const [narrative, setNarrative]   = useState<string | null>(initialNarrative);
  const [generating, setGenerating] = useState(false);
  const [error, setError]           = useState<string | null>(null);

  async function generate(regenerate = false) {
    setGenerating(true);
    setError(null);
    try {
      const url = `/api/projects/${projectId}/narrative${regenerate ? "?regenerate=true" : ""}`;
      const res = await fetch(url, { method: "POST" });
      const data = (await res.json()) as Partial<NarrativeResponse> & { error?: string };
      if (!res.ok) {
        setError(data.error ?? "Could not generate explanation.");
      } else {
        setNarrative(data.narrative ?? null);
      }
    } catch {
      setError("Network error — could not reach the server.");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-sm font-semibold text-slate-700">Explainable Fairness Report</h2>
        {narrative && !generating && (
          <button
            type="button"
            onClick={() => generate(true)}
            className="text-xs text-slate-400 hover:text-indigo-600 transition-colors"
          >
            Regenerate
          </button>
        )}
      </div>

      {/* No narrative yet */}
      {!narrative && !generating && (
        <div className="flex flex-col items-center py-8 gap-3 text-center">
          <p className="text-sm text-slate-500">
            The computed scores are ready. Generate an AI explanation when you need it.
          </p>
          <button
            type="button"
            onClick={() => generate(false)}
            className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors"
          >
            Generate explanation
          </button>
          {error && (
            <p className="text-xs text-red-600 max-w-sm">{error}</p>
          )}
        </div>
      )}

      {/* Loading */}
      {generating && (
        <div className="flex items-center gap-3 py-8 text-slate-500 text-sm">
          <svg
            className="animate-spin w-4 h-4 text-indigo-500 shrink-0"
            fill="none"
            viewBox="0 0 24 24"
          >
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path
              className="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
            />
          </svg>
          <span>Generating AI explanation…</span>
        </div>
      )}

      {/* Narrative */}
      {narrative && !generating && (
        <>
          <div className="text-slate-600 text-sm leading-relaxed space-y-3 [&_strong]:font-semibold [&_strong]:text-slate-800 [&_p]:mb-0">
            <ReactMarkdown>{narrative}</ReactMarkdown>
          </div>
          {error && (
            <p className="mt-3 text-xs text-red-600">{error}</p>
          )}
          <p className="mt-4 text-xs text-slate-400 italic">
            Generated by Gemini · Informational only — does not assign grades or replace instructor judgment.
          </p>
        </>
      )}
    </div>
  );
}
