import { useState } from "react";
import ReactMarkdown from "react-markdown";
import type { NarrativeResponse } from "@shared/types";
import { useAuth } from "../context/AuthContext";
import { BUTTON_PRIMARY, BUTTON_SECONDARY, CARD } from "./ui/styles";

interface Props {
  narrative: string | null;
  projectId: number;
  onNarrativeGenerated: (text: string) => void;
}

export function Narrative({ narrative, projectId, onNarrativeGenerated }: Props) {
  const { token } = useAuth();
  const [generating, setGenerating] = useState(false);
  const [error, setError]           = useState<string | null>(null);

  async function generate(regenerate = false) {
    setGenerating(true);
    setError(null);
    try {
      const url = `/api/projects/${projectId}/narrative${regenerate ? "?regenerate=true" : ""}`;
      const res = await fetch(url, {
        method:  "POST",
        headers: { Authorization: `Bearer ${token}` },
      });
      const data = (await res.json()) as Partial<NarrativeResponse> & { error?: string };
      if (!res.ok) {
        setError(data.error ?? "Could not generate explanation.");
      } else if (data.narrative) {
        onNarrativeGenerated(data.narrative);
      }
    } catch {
      setError("Network error — could not reach the server.");
    } finally {
      setGenerating(false);
    }
  }

  return (
    <section aria-labelledby="narrative-title" className={`${CARD} h-full min-w-0 border-l-4 border-l-purple-600 p-4`}>
      {/* Header */}
      <div className="mb-4 flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0">
          <h2 id="narrative-title" className="text-lg font-semibold text-slate-900">Explainable fairness report</h2>
          <p className="text-sm leading-normal text-slate-700">Scores computed by formula · explained by AI</p>
        </div>
        {narrative && !generating && (
          <button type="button" onClick={() => generate(true)} className={BUTTON_SECONDARY}>
            Regenerate
          </button>
        )}
      </div>

      {/* No narrative yet */}
      {!narrative && !generating && (
        <div className="flex flex-col items-center gap-3 py-6 text-center">
          <p className="text-sm leading-normal text-slate-700">
            The computed scores are ready. Generate an AI explanation when you need it.
          </p>
          <button type="button" onClick={() => generate(false)} className={BUTTON_PRIMARY}>
            Generate explanation
          </button>
          {error && (
            <p className="max-w-sm text-sm text-red-800">{error}</p>
          )}
        </div>
      )}

      {/* Loading */}
      {generating && (
        <div role="status" className="flex items-center gap-3 py-6 text-sm text-slate-700">
          <svg
            className="h-5 w-5 shrink-0 text-indigo-700 motion-safe:animate-spin"
            fill="none"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path
              className="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"
            />
          </svg>
          <span>Generating AI explanation…</span>
        </div>
      )}

      {/* Narrative */}
      {narrative && !generating && (
        <>
          <div className="text-sm leading-relaxed text-slate-800 [&_strong]:font-semibold [&_strong]:text-slate-900 [&_p]:mb-0 [&_p]:mt-3 [&_p:first-child]:mt-0 [&_p:not(:first-child)]:pt-3 [&_p:not(:first-child)]:border-t [&_p:not(:first-child)]:border-slate-200">
            <ReactMarkdown>{narrative}</ReactMarkdown>
          </div>
          {error && (
            <p className="mt-3 text-sm text-red-800">{error}</p>
          )}
          <p className="mt-4 text-sm italic leading-normal text-slate-700">
            Generated by Gemini · Informational only — does not assign grades or replace instructor judgment.
          </p>
        </>
      )}
    </section>
  );
}
