import type { StoredReportResponse, Flag } from "@shared/types";

const SOURCE_LABEL: Record<string, string> = {
  GITHUB:   "GitHub",
  EDITOR:   "FairTraze Docs",
  COMBINED: "GitHub + Docs",
};

const HEALTH_STYLE: Record<string, { bg: string; text: string; border: string }> = {
  "Healthy":       { bg: "#dcfce7", text: "#166534", border: "#86efac" },
  "Moderate Risk": { bg: "#fef9c3", text: "#713f12", border: "#fde047" },
  "High Risk":     { bg: "#fee2e2", text: "#7f1d1d", border: "#fca5a5" },
};

const FLAG_STYLE: Record<Flag, { bg: string; text: string; border: string; label: string }> = {
  "inactive":        { bg: "#fee2e2", text: "#991b1b", border: "#fca5a5", label: "Inactive" },
  "free-rider":      { bg: "#fee2e2", text: "#991b1b", border: "#fca5a5", label: "Free-rider" },
  "overload":        { bg: "#fff7ed", text: "#7c2d12", border: "#fed7aa", label: "Overload" },
  "deadline-driven": { bg: "#fefce8", text: "#713f12", border: "#fde047", label: "Deadline-driven" },
};

function barColor(flags: Flag[]): string {
  if (flags.includes("inactive") || flags.includes("free-rider")) return "#ef4444";
  if (flags.includes("overload")) return "#f97316";
  return "#4f46e5";
}

function stripMarkdown(text: string): string {
  return text
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1");
}

interface Props {
  stored: StoredReportResponse;
  narrative: string | null;
  assignmentLabel: string;
}

export function PrintableReport({ stored, narrative, assignmentLabel }: Props) {
  const { report, groupName, name, repoUrl, analyzedAt, sourceType } = stored;
  const healthStyle = HEALTH_STYLE[report.teamHealth] ?? HEALTH_STYLE["Healthy"];
  const equalShare  = report.memberCount > 0 ? (100 / report.memberCount).toFixed(1) : "—";
  const analysisDate = new Date(analyzedAt).toLocaleString();
  const printDate    = new Date(analyzedAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const repoDisplay = repoUrl.replace("https://github.com/", "github.com/");

  const summary = [
    { label: "Group",          value: groupName },
    { label: "App / Project",  value: name },
    { label: "Repository",     value: repoDisplay },
    { label: "Class / Subject",value: assignmentLabel || "—" },
    { label: "Source",         value: SOURCE_LABEL[sourceType ?? ""] ?? "GitHub" },
    { label: "Analyzed",       value: analysisDate },
  ];

  return (
    <div
      className="hidden print:block"
      style={{
        fontFamily: "'Outfit', system-ui, -apple-system, sans-serif",
        color: "#0f172a",
        background: "#fff",
        WebkitPrintColorAdjust: "exact",
        printColorAdjust: "exact",
      } as React.CSSProperties}
    >
      {/* ── Fixed page footer — repeats on every printed page ─────────────────── */}
      <div
        style={{
          position: "fixed",
          bottom: 0,
          left: 0,
          right: 0,
          padding: "7px 24px",
          borderTop: "1px solid #e2e8f0",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          fontSize: "8px",
          color: "#94a3b8",
          background: "#fff",
          letterSpacing: "0.01em",
        }}
      >
        <span>
          Generated by <strong style={{ color: "#64748b" }}>FAIR TRAZE AI</strong> — evidence to support
          instructor judgment; not a final grade.
        </span>
        <span>Generated {printDate}</span>
      </div>

      {/* ── Header band ────────────────────────────────────────────────────────── */}
      <div
        style={{
          background: "linear-gradient(135deg, #3730a3 0%, #4f46e5 55%, #6366f1 100%)",
          color: "#fff",
          padding: "22px 28px 18px",
        }}
      >
        {/* Wordmark */}
        <div style={{ display: "flex", alignItems: "center", gap: 9, marginBottom: 18 }}>
          <div
            style={{
              width: 30, height: 30, borderRadius: 7,
              background: "rgba(255,255,255,0.15)",
              display: "flex", alignItems: "center", justifyContent: "center",
              flexShrink: 0,
            }}
          >
            <svg width="15" height="15" fill="none" viewBox="0 0 24 24" stroke="white" strokeWidth={2.2}>
              <path strokeLinecap="round" strokeLinejoin="round"
                d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6m8 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0h6" />
            </svg>
          </div>
          <span style={{ fontWeight: 800, fontSize: 13, letterSpacing: "-0.02em", opacity: 0.95 }}>
            FAIR TRAZE AI
          </span>
          <span style={{ width: 1, height: 11, background: "rgba(255,255,255,0.3)", margin: "0 4px" }} />
          <span style={{ fontSize: 11, opacity: 0.65, fontWeight: 500 }}>
            Contribution Fairness Analysis
          </span>
        </div>

        {/* Title block */}
        <h1 style={{
          fontSize: 21, fontWeight: 800, margin: 0,
          letterSpacing: "-0.025em", lineHeight: 1.15,
        }}>
          Contribution Fairness Report
        </h1>
        <p style={{ fontSize: 12.5, margin: "5px 0 0", opacity: 0.85, fontWeight: 600 }}>
          {groupName}
          {name && groupName !== name && <> · {name}</>}
        </p>
        {assignmentLabel && (
          <p style={{ fontSize: 10.5, margin: "3px 0 0", opacity: 0.55, fontWeight: 400 }}>
            {assignmentLabel}
          </p>
        )}
      </div>

      {/* ── Summary band ───────────────────────────────────────────────────────── */}
      <div
        style={{
          background: "#f8fafc",
          borderBottom: "2px solid #e2e8f0",
          padding: "14px 28px",
        }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(3, 1fr)",
            gap: "10px 28px",
          }}
        >
          {summary.map(({ label, value }) => (
            <div key={label} style={{ breakInside: "avoid" }}>
              <p style={{
                fontSize: 8, fontWeight: 700, color: "#64748b",
                textTransform: "uppercase", letterSpacing: "0.08em",
                margin: "0 0 2px",
              }}>
                {label}
              </p>
              <p style={{
                fontSize: 11, fontWeight: 600, color: "#0f172a",
                margin: 0, wordBreak: "break-all", lineHeight: 1.4,
              }}>
                {value}
              </p>
            </div>
          ))}

          {/* Team health */}
          <div style={{ display: "flex", alignItems: "center", gap: 14, breakInside: "avoid" }}>
            <div>
              <p style={{
                fontSize: 8, fontWeight: 700, color: "#64748b",
                textTransform: "uppercase", letterSpacing: "0.08em", margin: "0 0 3px",
              }}>
                Team Health
              </p>
              <span style={{
                display: "inline-block",
                padding: "2px 9px",
                borderRadius: 999,
                fontSize: 10.5, fontWeight: 700,
                background: healthStyle.bg,
                color: healthStyle.text,
                border: `1px solid ${healthStyle.border}`,
              }}>
                {report.teamHealth}
              </span>
            </div>
            <div>
              <p style={{
                fontSize: 8, fontWeight: 700, color: "#64748b",
                textTransform: "uppercase", letterSpacing: "0.08em", margin: "0 0 2px",
              }}>
                Gini
              </p>
              <p style={{ fontSize: 14, fontWeight: 800, color: "#0f172a", margin: 0 }}>
                {report.gini.toFixed(3)}
              </p>
            </div>
          </div>

          {/* Member count */}
          <div style={{ breakInside: "avoid" }}>
            <p style={{
              fontSize: 8, fontWeight: 700, color: "#64748b",
              textTransform: "uppercase", letterSpacing: "0.08em", margin: "0 0 2px",
            }}>
              Members
            </p>
            <p style={{ fontSize: 14, fontWeight: 800, color: "#0f172a", margin: 0 }}>
              {report.memberCount}
            </p>
          </div>
        </div>
      </div>

      {/* ── Section: Contribution Profiling ────────────────────────────────────── */}
      <div style={{ padding: "22px 28px 0" }}>
        {/* Section heading */}
        <div style={{ display: "flex", alignItems: "center", gap: 9, marginBottom: 13 }}>
          <div style={{ width: 3, height: 15, background: "#4f46e5", borderRadius: 2, flexShrink: 0 }} />
          <h2 style={{ fontSize: 12, fontWeight: 700, margin: 0, color: "#1e293b", letterSpacing: "-0.01em" }}>
            Contribution Profiling
          </h2>
          <span style={{
            fontSize: 9, fontWeight: 600,
            color: "#4f46e5", background: "#eef2ff",
            border: "1px solid #c7d2fe",
            borderRadius: 4, padding: "1px 6px",
          }}>
            {SOURCE_LABEL[sourceType ?? ""] ?? "GitHub"}
          </span>
        </div>

        {/* Member table */}
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 11 }}>
          <thead>
            <tr style={{ background: "#f1f5f9" }}>
              {[
                { label: "Member",            align: "left",   width: "auto" },
                { label: "Share",             align: "right",  width: 40 },
                { label: "",                  align: "left",   width: 72 },
                { label: "Commits",           align: "right",  width: 56 },
                { label: "Active Days",       align: "right",  width: 72 },
                { label: "Weighted Lines",    align: "right",  width: 88 },
                { label: "Flags",             align: "left",   width: 140 },
              ].map(({ label, align, width }) => (
                <th
                  key={label}
                  style={{
                    textAlign: align as "left" | "right",
                    padding: "6px 8px",
                    fontSize: 8, fontWeight: 700, color: "#475569",
                    textTransform: "uppercase", letterSpacing: "0.06em",
                    borderTop: "1px solid #e2e8f0",
                    borderBottom: "1px solid #e2e8f0",
                    whiteSpace: "nowrap",
                    width: width === "auto" ? undefined : width,
                  }}
                >
                  {label}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {report.members.map((m, i) => {
              const sharePct = (m.contributionShare * 100).toFixed(1);
              const barFill  = Math.min(m.contributionShare * 100, 100);
              return (
                <tr
                  key={m.githubUsername}
                  style={{
                    background: i % 2 === 0 ? "#ffffff" : "#f8fafc",
                    breakInside: "avoid",
                    pageBreakInside: "avoid",
                  }}
                >
                  {/* Member name */}
                  <td style={{
                    padding: "8px 8px",
                    fontWeight: 700, color: "#1e293b",
                    borderBottom: "1px solid #f1f5f9",
                  }}>
                    {m.studentName}
                    <span style={{
                      display: "block", fontSize: 8.5,
                      color: "#94a3b8", fontWeight: 400, marginTop: 1,
                    }}>
                      @{m.githubUsername}
                    </span>
                  </td>

                  {/* Share % */}
                  <td style={{
                    padding: "8px 8px",
                    textAlign: "right",
                    fontWeight: 800, fontSize: 12, color: "#1e293b",
                    borderBottom: "1px solid #f1f5f9",
                    whiteSpace: "nowrap",
                  }}>
                    {sharePct}%
                  </td>

                  {/* Bar */}
                  <td style={{ padding: "8px 6px", borderBottom: "1px solid #f1f5f9" }}>
                    <div style={{
                      height: 7, background: "#e2e8f0",
                      borderRadius: 4, overflow: "hidden",
                      minWidth: 60,
                    }}>
                      <div style={{
                        height: "100%",
                        width: `${barFill}%`,
                        background: barColor(m.flags),
                        borderRadius: 4,
                      }} />
                    </div>
                  </td>

                  {/* Commits */}
                  <td style={{
                    padding: "8px 8px",
                    textAlign: "right", color: "#334155",
                    borderBottom: "1px solid #f1f5f9",
                  }}>
                    {m.commits}
                  </td>

                  {/* Active days */}
                  <td style={{
                    padding: "8px 8px",
                    textAlign: "right", color: "#334155",
                    borderBottom: "1px solid #f1f5f9",
                  }}>
                    {m.activeDays}
                  </td>

                  {/* Weighted lines */}
                  <td style={{
                    padding: "8px 8px",
                    textAlign: "right", color: "#334155",
                    borderBottom: "1px solid #f1f5f9",
                  }}>
                    {m.weightedAdditions.toLocaleString(undefined, { maximumFractionDigits: 0 })}
                  </td>

                  {/* Flags */}
                  <td style={{ padding: "8px 8px", borderBottom: "1px solid #f1f5f9" }}>
                    <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                      {m.flags.length === 0 ? (
                        <span style={{ color: "#94a3b8", fontSize: 9.5, fontStyle: "italic" }}>
                          No flags
                        </span>
                      ) : (
                        m.flags.map((flag) => {
                          const s = FLAG_STYLE[flag];
                          return (
                            <span
                              key={flag}
                              style={{
                                display: "inline-block",
                                padding: "2px 6px",
                                borderRadius: 4,
                                fontSize: 8.5, fontWeight: 700,
                                background: s.bg, color: s.text,
                                border: `1px solid ${s.border}`,
                                whiteSpace: "nowrap",
                              }}
                            >
                              {s.label}
                            </span>
                          );
                        })
                      )}
                    </div>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>

        {/* Table legend */}
        <div style={{
          display: "flex", gap: 20, marginTop: 9,
          fontSize: 8.5, color: "#64748b", flexWrap: "wrap",
          alignItems: "center",
        }}>
          <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
            <span style={{ display: "inline-block", width: 10, height: 10, background: "#4f46e5", borderRadius: 2 }} />
            Normal
          </span>
          <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
            <span style={{ display: "inline-block", width: 10, height: 10, background: "#ef4444", borderRadius: 2 }} />
            Free-rider / Inactive
          </span>
          <span style={{ display: "flex", alignItems: "center", gap: 4 }}>
            <span style={{ display: "inline-block", width: 10, height: 10, background: "#f97316", borderRadius: 2 }} />
            Overload
          </span>
          <span style={{ marginLeft: "auto" }}>
            Equal share = <strong>{equalShare}%</strong> &nbsp;·&nbsp;
            Healthy: Gini &lt; 0.2 &nbsp;·&nbsp; Moderate Risk: 0.2–0.4 &nbsp;·&nbsp; High Risk: ≥ 0.4
          </span>
        </div>
      </div>

      {/* ── Section: Explainable Fairness Analysis ─────────────────────────────── */}
      {narrative && (
        <div style={{ padding: "24px 28px 0" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 9, marginBottom: 13 }}>
            <div style={{ width: 3, height: 15, background: "#4f46e5", borderRadius: 2, flexShrink: 0 }} />
            <h2 style={{ fontSize: 12, fontWeight: 700, margin: 0, color: "#1e293b", letterSpacing: "-0.01em" }}>
              Explainable Fairness Analysis
            </h2>
            <span style={{ fontSize: 9, color: "#94a3b8", fontStyle: "italic" }}>
              AI-generated narrative (Gemini)
            </span>
          </div>

          <div style={{
            border: "1px solid #e2e8f0",
            borderLeft: "3px solid #6366f1",
            borderRadius: 6,
            padding: "16px 18px",
            background: "#fafafa",
          }}>
            {stripMarkdown(narrative)
              .split(/\n{2,}/)
              .filter((p) => p.trim())
              .map((para, i) => (
                <p key={i} style={{
                  fontSize: 11, lineHeight: 1.75, color: "#334155",
                  margin: i === 0 ? 0 : "10px 0 0",
                }}>
                  {para.trim()}
                </p>
              ))}
          </div>

          <p style={{
            fontSize: 8.5, color: "#94a3b8", marginTop: 8,
            fontStyle: "italic", lineHeight: 1.5,
          }}>
            AI narrative is informational only — it does not assign grades, does not override instructor judgment,
            and must not be cited as a final assessment.
          </p>
        </div>
      )}

      {/* Spacer above fixed footer */}
      <div style={{ height: 36 }} />
    </div>
  );
}
