export function ScopeLegend() {
  return (
    <div className="flex items-start gap-3 px-4 py-3 rounded-lg bg-indigo-50 border border-indigo-100 text-xs text-indigo-700 flex-wrap">
      <span className="font-semibold shrink-0">Prototype scope:</span>
      <span>
        This report was generated by the implemented pipeline —{" "}
        <span className="font-medium">
          Data Collection · Contribution Profiling · Participation Imbalance Detection · AI-Assisted Analysis · Explainable Fairness Reporting
        </span>
        . Future modules (Collaborative Editor, multi-role access, admin analytics) are designed but not yet built.
      </span>
    </div>
  );
}
